### ISSUE TITLE
EC2へのSSH接続時のアクセス制限について

### ISSUE THREAD

**Issue by bigmuramura** [shujishigenobu/omics-collab-cm-nibb#1]
初学者向けのEC2への接続方法の手順を検討中です。

@shujishigenobu 
SSH接続用のセキュリティグループのアクセス元制限をかけるか、制限をかけないかご意見いただきたいです。
EC2を作成するタイミングにも依るかなと思うのですがどちらを想定されていましたでしょうか？

講義日までに受講者側でEC2作成までやっておいてもらう場合
- 準備したときは接続できたが、講義の日になって接続できないことが起きうる

講義日にEC2作成からはじめる
- その場でセキュリティグループを作成するのでまず問題ない

特定のソースからのIP制限をかけた方が間違いなく良いのですが、接続トラブル対策で0.0.0.0/0としている手順が多いのも現状です。
AWSの勉強にフォーカスするならセッションマネージャーがベストなのですけど、解析の演習するのが目的ですし。

**Comment by shujishigenobu** [comment]
基本的には、制限をかけないで、0.0.0.0/0　としておいて下さい。
その上で、補足の段落を設けて、その中で、セキュリティ対策上制限した方が良いと説明し、その方法も説明して下さい。
基本ワークフローでは、なるだけ環境構築に躓かずに完走するということを第一目標とし、そのため環境構築の手順はミニマムなものにする方針で。発展的な内容は補足で追記するスタイルで、この後もお願いします。

**Comment by bigmuramura** [comment]
手順作成の方針、承知しました。ありがとうございます。
