### ISSUE TITLE
シロイヌナズナ紹介の写真が欲しい

### ISSUE THREAD

**Issue by bigmuramura** [shujishigenobu/omics-collab-cm-nibb#2]
冒頭の説明のあとに、2D sampleと2D2L sampleで育ったときの写真が1枚があるとこれから取り組む生物をイメージしやすくて助かります。
有名なモデルなので生物界隈では当たり前かもしれないですが、シロイヌナズナに馴染みない我々は最初にググってどんな植物なのか？からはじめました。

この様な写真が一枚あると本当の初学者としては嬉しいです。

https://www2.sci.hokudai.ac.jp/dept/bio/organism/675

**Comment by bigmuramura** [comment]
著作権的にこちらのリンクを貼るのが早そうです。
2D Sampleの例はあれば嬉しいですけど、植物の外観がわかれば嬉しい程度ですので。

https://www.nibb.ac.jp/webmag/field/okazaki/2005/05/arabidopsis.html

**Comment by shujishigenobu** [comment]
[シロイヌナズナ Arabidopsis thaliana とは？@基礎生物学研究所](https://www.nibb.ac.jp/webmag/field/okazaki/2005/05/arabidopsis.html)
    [モデル生物の世界「シロイヌナズナ」（動画 基礎生物学研究所)](https://www.youtube.com/watch?v=wOJdo9vR8Qg)
を追加。
