### ISSUE TITLE
hisat2のreportの使い所

### ISSUE THREAD

**Issue by bigmuramura** [shujishigenobu/omics-collab-cm-nibb#6]
> hisat2実行時にmappning stats情報がreportされる。これは記録しておくとよい。

reportの内容は何に必要でどこで使われるのでしょうか？

## 関連したところで

> また後述のmultiqcで、さらにまとめたreportを得ることもできる。

multiqcは補足で別途追加予定でしょうか？

以下を参考にしました。

[様々なバイオインフォマティクスツールの分析結果を１つに集約して分析できる MultiQC \- macでインフォマティクス](https://kazumaxneo.hatenablog.com/entry/2018/01/19/180954)

**Comment by shujishigenobu** [comment]
> これはマッピング率など実験の成否を評価できる数値であるので
と理由を追加。
