### ISSUE TITLE
pl1 sup01 edgeR_batchrun　動作確認

### ISSUE THREAD

**Issue by shujishigenobu** [shujishigenobu/omics-collab-cm-nibb#7]
スクリプトでR/edgeRを実行する、pl1 sup01 edgeR_batchrun を作成しました。
大村さん、動作確認をお願いします。

**Comment by bigmuramura** [comment]
@shujishigenobu 
スクリプト化ありがとうございます。
トレーニング手順通り作成した環境でRスクリプト実行し問題ありませんでした。
