### ISSUE TITLE
CFnテンプレートをマネコン操作のリソースの内容と合わせる

### ISSUE THREAD

**Issue by bigmuramura** [shujishigenobu/omics-collab-cm-nibb#9]
Set up AWSのマネコンから作成したリソースと合わせられるものは合わしたいので現状ですと以下追加お願いします。

- EC2にNameタグ付与
    - handson-ec2
 - SecurityGroupにNameタグ付与
     -  handson-ec2-sg
 - VPC,サブネット、その他リソースにNameタグ付与
      - Set up AWSはデフォルトVPCを利用しているため、handson-vpcなどわかりやすい名前付けてもらえばOK 
 - EBSのボリュームサイズは30GB
 - EBS最適化はどちらかを検討
      - t3a.xlargeだけなら無効のままで問題ない。インスタンスタイプはt3a.xlarge固定にする。
      - EBS最適化インスタンスタイプも含め選択式で指定するのであれば最適化有効にするほうが良い

**Comment by Keisuke-Hiraki** [comment]
>EC2にNameタグ付与
handson-ec2
SecurityGroupにNameタグ付与
handson-ec2-sg
VPC,サブネット、その他リソースにNameタグ付与
Set up AWSはデフォルトVPCを利用しているため、handson-vpcなどわかりやすい名前付けてもらえばOK
EBSのボリュームサイズは30GB

上記内容反映完了しました。

> EBS最適化はどちらかを検討

インスタンスタイプはt3a.xlarge固定にするほうで修正しました。

**Comment by bigmuramura** [comment]
@Keisuke-Hiraki 
確認済みです！対応ありがございました。
